---
title: "Assignment 1, Create"
author: "Erin M. Ochoa"
date: "2018/04/10"
output: github_document
---

```{r setup}
library(dplyr)
library(ggplot2)
theme_set(theme_grey())
```



```{r load, eval=FALSE}
# Downloaded from https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present-Dashboard/5cd6-ry5g

crimes <- read.csv('/Users/erin/Google Drive/School/2018 Spring/Data Viz/Assignments/HW1/Crimes_-_2001_to_present.csv')

```


```{r inspect}
names(crimes)
head(crimes)
```

```{r subset, eval=FALSE}
keep <- c('Year','Primary.Type','Arrest','Domestic','Community.Area')
crimes.sub <- crimes[,keep]
crimes.sub <- crimes.sub[(crimes.sub$Year < 2018), ]
write.csv(crimes.sub,'/Users/erin/Google Drive/School/2018 Spring/Data Viz/Assignments/HW1/crimes_sub.csv',row.names = FALSE)
rm(crimes)
```

```{r subset2}
crimes.sub <- crimes.sub[(crimes.sub$Year == 2017), ]
```



```{r subset3}
crimes.sub %>% 
  group_by(Primary.Type) %>%
  summarise(num_rows = length(Primary.Type)) %>%
  data.frame() -> df_crimes

#Keep the 10 most common crimes (excluding the nebulous 'Other Offense' category)
keep_cats <- df_crimes[ order(-df_crimes[2]), ]
keep_cats <- unlist(list(as.character(keep_cats[(1:11), "Primary.Type"])))
keep_cats <- keep_cats[keep_cats != 'OTHER OFFENSE']

crimes.final <- crimes.sub[as.character(crimes.sub$Primary.Type) %in% keep_cats, ]
crimes.final$Primary.Type <- factor(crimes.final$Primary.Type, levels = keep_cats)
```

```{r calc_props}
df_crimes$prop <- df_crimes$num_rows / sum(df_crimes$num_rows)
df_crimes.sub <- df_crimes[as.character(df_crimes$Primary.Type) %in% keep_cats, ]
df_crimes.sub$Primary.Type <- factor(df_crimes.sub$Primary.Type, levels = keep_cats)
df_crimes.sub <- df_crimes.sub[ order(-df_crimes.sub[3]), ]
```


```{r labs}
leg_labels <- tools::toTitleCase(sapply(keep_cats, tolower,USE.NAMES = FALSE))
leg_labels <- gsub(" ", "\n", leg_labels, perl=TRUE)
```

```{r viz}
ggplot(df_crimes.sub,aes(Primary.Type,prop)) + geom_bar(stat='identity',aes(fill=Primary.Type)) +
      theme(legend.position = 'none',legend.title = element_blank(),panel.border = element_rect(linetype = "solid", color = "grey70", fill=NA, size=1.1),
            plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5),axis.title.x=element_blank()) +
      scale_fill_brewer(palette = "Paired") +
      scale_y_continuous(labels = scales::percent_format()) +
      scale_x_discrete(labels=leg_labels) +
      labs(y='Proportion of Total Reported Crimes',title='Most Commonly Reported Types of Crime in Chicago, 2017')

```

```{r arrests_calc}
#Get prop of each type and arrest status
crimes.sub %>% 
  group_by(Primary.Type,Arrest) %>%
  summarise(num_rows = length(Primary.Type)) %>%
  data.frame() -> df.crimes

df.crimes$prop <- df.crimes$num_rows / sum(df.crimes$num_rows)
df.crimes.sub <- df.crimes[as.character(df.crimes$Primary.Type) %in% keep_cats, ]
df.crimes.sub$Primary.Type <- factor(df.crimes.sub$Primary.Type, levels = keep_cats)
df.crimes.sub <- df.crimes.sub[ order(-df.crimes.sub[3]), ]

df.crimes.sub
```

```{r viz2}
ggplot(df.crimes.sub,aes(Primary.Type,prop,Arrest)) + geom_bar(stat='identity',aes(fill=Primary.Type,alpha=Arrest))+#,color=Arrest)) +
      theme(legend.position = 'none',legend.title = element_blank(),#panel.border = element_rect(linetype="solid",color='transparent', fill=NA, size=1.1),
            plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5),axis.title.x=element_blank(),
            panel.background = element_blank(),panel.grid.major.y=element_line(colour='black'),panel.grid.major.x=element_blank()) +
      scale_fill_brewer(palette='Paired') +
      scale_alpha_discrete(range = c(.6,1)) + 
      scale_y_continuous(labels = scales::percent_format(),limits=c(0,.25)) +
      scale_x_discrete(labels=leg_labels) +
      labs(y='Proportion of Total Reported Crimes',title='Most Commonly Reported Types of Crime in Chicago, 2017')
```
